@startuml
abstract class Individual
annotation java.lang.Override
annotation java.lang.SuppressWarnings
class CashPayment
class CreditCardPayment
class Customer
class Inventory
class InventoryGUI
class InventoryLoader
class MainMenuGUI
class Menu
class MenuCLI
class OrderMenuGUI
class OrderSystem
class Payment
class PointSystem
class Restaurant
class RestaurantInfoGUI
class SellGUI
class Staff
class StaffGUI
class java.io.BufferedReader
class java.io.BufferedWriter
class java.io.FileReader
class java.io.FileWriter
class java.io.IOException
class java.time.LocalDate
class java.time.LocalTime
class java.time.format.DateTimeFormatter
class java.util.ArrayList
class java.util.HashMap
class java.util.List
class java.util.Map
class java.util.Scanner
class java.util.function.Consumer
class java.util.stream.Collectors
class javax.swing.JFrame
class javax.swing.JOptionPane
class javax.swing.table.DefaultTableModel
CashPayment ..> java.lang.Override
CashPayment --|> Payment
CreditCardPayment ..> java.lang.Override
CreditCardPayment --|> Payment
Customer --|> Individual
Customer ..> java.util.HashMap
Customer ..> java.util.Map
InventoryGUI ..> java.lang.SuppressWarnings
InventoryGUI ..> java.io.BufferedReader
InventoryGUI ..> java.io.FileReader
InventoryGUI ..> java.io.FileWriter
InventoryGUI --|> javax.swing.JFrame
InventoryGUI ..> javax.swing.JOptionPane
InventoryGUI ..> javax.swing.table.DefaultTableModel
InventoryLoader ..> java.util.ArrayList
InventoryLoader ..> java.util.List
MainMenuGUI ..> java.lang.SuppressWarnings
MainMenuGUI --|> javax.swing.JFrame
Menu ..> java.util.HashMap
Menu ..> java.util.Map
Menu ..> java.util.function.Consumer
MenuCLI ..> java.util.Scanner
OrderMenuGUI ..> java.lang.SuppressWarnings
OrderMenuGUI --|> javax.swing.JFrame
OrderSystem ..> java.lang.Override
OrderSystem ..> java.time.LocalDate
OrderSystem ..> java.time.LocalTime
OrderSystem ..> java.time.format.DateTimeFormatter
OrderSystem ..> java.util.ArrayList
OrderSystem ..> java.util.HashMap
OrderSystem ..> java.util.Scanner
PointSystem ..> java.util.HashMap
Restaurant ..> java.io.BufferedReader
Restaurant ..> java.io.BufferedWriter
Restaurant ..> java.io.FileReader
Restaurant ..> java.io.FileWriter
Restaurant ..> java.io.IOException
Restaurant ..> java.util.stream.Collectors
RestaurantInfoGUI ..> java.lang.SuppressWarnings
RestaurantInfoGUI --|> javax.swing.JFrame
SellGUI ..> java.lang.SuppressWarnings
SellGUI --|> javax.swing.JFrame
Staff --|> Individual
StaffGUI ..> java.lang.SuppressWarnings
StaffGUI ..> java.io.BufferedReader
StaffGUI ..> java.io.FileReader
StaffGUI ..> java.io.FileWriter
StaffGUI --|> javax.swing.JFrame
StaffGUI ..> javax.swing.JOptionPane
StaffGUI ..> javax.swing.table.DefaultTableModel
@enduml